/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    testimonials: Testimonial;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    styling: Styling;
    settings: Setting;
    header: Header;
    cta: Cta;
    seo: Seo;
    homepage: Homepage;
    home: Home;
    team: Team;
    programma: Programma;
    resultaten: Resultaten;
  };
  globalsSelect: {
    styling: StylingSelect<false> | StylingSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    cta: CtaSelect<false> | CtaSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    programma: ProgrammaSelect<false> | ProgrammaSelect<true>;
    resultaten: ResultatenSelect<false> | ResultatenSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Wordt automatisch gegenereerd op basis van "title" als dit leeg blijft.
   */
  slug?: string | null;
  /**
   * Verberg dit voor bezoekers. Alleen ingelogde beheerders kunnen het dan nog bekijken.
   */
  private?: boolean | null;
  layout?:
    | (
        | HeaderBlock
        | TextBlock
        | HeadingBlock
        | ImageBlock
        | TextImageBlock
        | ReviewsBlock
        | ResultsBlock
        | VideoBlock
        | FaqBlock
        | CardsBlock
      )[]
    | null;
  /**
   * Overschrijft de standaard SEO-instellingen uit de SEO-global voor deze pagina.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * Alleen invullen om de standaard canonical URL te overschrijven.
     */
    canonicalURL?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderBlock".
 */
export interface HeaderBlock {
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  image?: (number | null) | Media;
  ctaLabel?: string | null;
  /**
   * Intern pad (bijv. /programma) of volledige URL.
   */
  ctaUrl?: string | null;
  ctaHelperText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'header';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Beschrijving van de afbeelding of video voor toegankelijkheid en SEO.
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingBlock".
 */
export interface HeadingBlock {
  heading: string;
  level: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
  alignment: 'left' | 'center' | 'right';
  id?: string | null;
  blockName?: string | null;
  blockType: 'heading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  image: number | Media;
  /**
   * Overschrijft de alt-tekst van de media als dit is ingevuld.
   */
  altText?: string | null;
  caption?: string | null;
  alignment: 'left' | 'center' | 'right';
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextImageBlock".
 */
export interface TextImageBlock {
  eyebrow?: string | null;
  heading?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  imagePosition: 'right' | 'left';
  id?: string | null;
  blockName?: string | null;
  blockType: 'textImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewsBlock".
 */
export interface ReviewsBlock {
  heading?: string | null;
  items?:
    | {
        title: string;
        quote: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'reviews';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResultsBlock".
 */
export interface ResultsBlock {
  heading?: string | null;
  columns: '3' | '4';
  stats?:
    | {
        /**
         * Bijv. "500" of "-12"
         */
        value: string;
        /**
         * Bijv. "+" of "kg"
         */
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'results';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  heading?: string | null;
  /**
   * Upload een videobestand.
   */
  video: number | Media;
  caption?: string | null;
  aspectRatio: '16/9' | '9/16' | '1/1';
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  heading?: string | null;
  subtext?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsBlock".
 */
export interface CardsBlock {
  heading?: string | null;
  columns: '2' | '3';
  items?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  quote: string;
  image?: (number | null) | Media;
  /**
   * Bijv. "-12 kg in 16 weken" of "Klant sinds 2023".
   */
  result?: string | null;
  /**
   * Uitgelichte testimonials kunnen prominent getoond worden op de site.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  private?: T;
  layout?:
    | T
    | {
        header?: T | HeaderBlockSelect<T>;
        text?: T | TextBlockSelect<T>;
        heading?: T | HeadingBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        textImage?: T | TextImageBlockSelect<T>;
        reviews?: T | ReviewsBlockSelect<T>;
        results?: T | ResultsBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        cards?: T | CardsBlockSelect<T>;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderBlock_select".
 */
export interface HeaderBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  image?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  ctaHelperText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingBlock_select".
 */
export interface HeadingBlockSelect<T extends boolean = true> {
  heading?: T;
  level?: T;
  alignment?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  altText?: T;
  caption?: T;
  alignment?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextImageBlock_select".
 */
export interface TextImageBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  content?: T;
  image?: T;
  imagePosition?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewsBlock_select".
 */
export interface ReviewsBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        title?: T;
        quote?: T;
        name?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResultsBlock_select".
 */
export interface ResultsBlockSelect<T extends boolean = true> {
  heading?: T;
  columns?: T;
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  heading?: T;
  video?: T;
  caption?: T;
  aspectRatio?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  heading?: T;
  subtext?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsBlock_select".
 */
export interface CardsBlockSelect<T extends boolean = true> {
  heading?: T;
  columns?: T;
  items?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  quote?: T;
  image?: T;
  result?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Kleuren en lettertypes voor de hele site. Wijzigingen zijn direct site-breed zichtbaar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "styling".
 */
export interface Styling {
  id: number;
  colors: {
    /**
     * Hexcode, bijv. #c8a464
     */
    pageBackground: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    cardBackground: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    lightCard: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    cardGradientFrom: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    cardGradientTo: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    standardBorder: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    thinDivider: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    bronzeBorder: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    primaryText: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    mutedBodyText: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    smallText: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    vagueLabels: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    darkTextOnIvory: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    navyTextOnGold: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    primaryGold: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    goldHover: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    lightGold: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    lightGoldHover: string;
    /**
     * Hexcode, bijv. #c8a464
     */
    starRating: string;
  };
  typography: {
    /**
     * Naam van een Google Font, bijv. Montserrat
     */
    headingFontFamily: string;
    /**
     * Puntkomma-gescheiden, bijv. 700;800
     */
    headingWeights: string;
    headingWeight: '700' | '800';
    headingLetterSpacing: string;
    wordmarkLetterSpacing: string;
    /**
     * Naam van een Google Font, bijv. Inter
     */
    bodyFontFamily: string;
    /**
     * Puntkomma-gescheiden, bijv. 400;500;600;700
     */
    bodyWeights: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  companyName: string;
  logo?: (number | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: {
      street?: string | null;
      postalCode?: string | null;
      city?: string | null;
      country?: string | null;
    };
    legalName?: string | null;
    kvkNumber?: string | null;
    vatNumber?: string | null;
  };
  socialMedia?:
    | {
        platform: 'instagram' | 'facebook' | 'linkedin' | 'tiktok' | 'youtube' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  footer?: {
    /**
     * Korte zin onder het logo in de footer, bijv. "Bouw een leefstijl die niet instort zodra het leven druk wordt."
     */
    tagline?: string | null;
    columns?:
      | {
          title: string;
          links?:
            | {
                link: {
                  label: string;
                  /**
                   * Intern pad (bijv. /over-mij) of volledige URL (bijv. https://...)
                   */
                  url: string;
                  newTab?: boolean | null;
                };
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Bijv. Privacyverklaring, Algemene voorwaarden, Cookiebeleid.
     */
    legalLinks?:
      | {
          link: {
            label: string;
            /**
             * Intern pad (bijv. /over-mij) of volledige URL (bijv. https://...)
             */
            url: string;
            newTab?: boolean | null;
          };
          id?: string | null;
        }[]
      | null;
    copyrightText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          label: string;
          /**
           * Intern pad (bijv. /over-mij) of volledige URL (bijv. https://...)
           */
          url: string;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  showCta?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Standaard call-to-action, herbruikbaar op meerdere plekken in de site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta".
 */
export interface Cta {
  id: number;
  heading?: string | null;
  text?: string | null;
  buttonLabel?: string | null;
  buttonUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Standaardwaarden die worden gebruikt wanneer een pagina geen eigen SEO-data heeft.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  /**
   * Alleen invullen om de standaard canonical URL te overschrijven.
   */
  canonicalURL?: string | null;
  noIndex?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Verberg dit voor bezoekers. Alleen ingelogde beheerders kunnen het dan nog bekijken.
   */
  private?: boolean | null;
  hero?: {
    ratingValue?: string | null;
    ratingLabel?: string | null;
    heading?: string | null;
    intro?: string | null;
    image?: (number | null) | Media;
    memberBadgeText?: string | null;
  };
  stats?:
    | {
        value: string;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  problem?: {
    heading?: string | null;
    intro1?: string | null;
    intro2?: string | null;
    cards?:
      | {
          title: string;
          text: string;
          highlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  philosophy?: {
    heading?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
  };
  pillars?: {
    heading?: string | null;
    subtext?: string | null;
    items?:
      | {
          title: string;
          text: string;
          image?: (number | null) | Media;
          reversed?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  journey?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: string | null;
    image?: (number | null) | Media;
    steps?:
      | {
          phase: string;
          title: string;
          text: string;
          highlight?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  testimonials?: {
    heading?: string | null;
    items?:
      | {
          title?: string | null;
          quote: string;
          id?: string | null;
        }[]
      | null;
  };
  community?: {
    heading?: string | null;
    subtext?: string | null;
    memberCountText?: string | null;
    memberCountLabel?: string | null;
    photos?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    starsHeading?: string | null;
    starsSubtext?: string | null;
    starsVideos?:
      | {
          video?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  aboutSam?: {
    heading?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
    closingLine?: string | null;
    horizontalImage?: (number | null) | Media;
    image1?: (number | null) | Media;
    image2?: (number | null) | Media;
    bottomImage?: (number | null) | Media;
  };
  team?: {
    heading?: string | null;
    subtext?: string | null;
    groupImage?: (number | null) | Media;
    members?:
      | {
          image?: (number | null) | Media;
          name: string;
          role: string;
          bio: string;
          id?: string | null;
        }[]
      | null;
  };
  content?: {
    heading?: string | null;
    videos?:
      | {
          video?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  faq?: {
    heading?: string | null;
    subtext?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Verberg dit voor bezoekers. Alleen ingelogde beheerders kunnen het dan nog bekijken.
   */
  private?: boolean | null;
  hero?: {
    ratingValue?: string | null;
    ratingLabel?: string | null;
    heading?: string | null;
    intro?: string | null;
    image?: (number | null) | Media;
    memberBadgeText?: string | null;
  };
  stats?:
    | {
        value: string;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  problem?: {
    heading?: string | null;
    intro1?: string | null;
    intro2?: string | null;
    cards?:
      | {
          title: string;
          text: string;
          highlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  philosophy?: {
    heading?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
  };
  pillars?: {
    heading?: string | null;
    subtext?: string | null;
    items?:
      | {
          title: string;
          text: string;
          image?: (number | null) | Media;
          reversed?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  journey?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: string | null;
    image?: (number | null) | Media;
    steps?:
      | {
          phase: string;
          title: string;
          text: string;
          highlight?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  results?: {
    heading?: string | null;
    images?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  stories?: {
    heading?: string | null;
    subtext?: string | null;
    items?:
      | {
          /**
           * Bijv. "Verhaal 01"
           */
          eyebrowLabel: string;
          title: string;
          text: string;
          name: string;
          /**
           * Eén foto toont een vaste afbeelding, meerdere foto's tonen een swipebare carrousel.
           */
          photos?:
            | {
                image?: (number | null) | Media;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  testimonials?: {
    heading?: string | null;
    items?:
      | {
          title?: string | null;
          quote: string;
          id?: string | null;
        }[]
      | null;
  };
  community?: {
    heading?: string | null;
    subtext?: string | null;
    memberCountText?: string | null;
    memberCountLabel?: string | null;
    photos?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    starsHeading?: string | null;
    starsSubtext?: string | null;
    starsVideos?:
      | {
          video?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  aboutSam?: {
    heading?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
    closingLine?: string | null;
    horizontalImage?: (number | null) | Media;
    image1?: (number | null) | Media;
    image2?: (number | null) | Media;
    bottomImage?: (number | null) | Media;
  };
  team?: {
    heading?: string | null;
    subtext?: string | null;
    groupImage?: (number | null) | Media;
    members?:
      | {
          image?: (number | null) | Media;
          name: string;
          role: string;
          bio: string;
          id?: string | null;
        }[]
      | null;
  };
  content?: {
    heading?: string | null;
    videos?:
      | {
          video?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  faq?: {
    heading?: string | null;
    subtext?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  /**
   * Verberg dit voor bezoekers. Alleen ingelogde beheerders kunnen het dan nog bekijken.
   */
  private?: boolean | null;
  hero?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: string | null;
    image?: (number | null) | Media;
  };
  stats?:
    | {
        value: string;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  founder?: {
    eyebrow?: string | null;
    name?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
    specialisme?: string | null;
    ervaring?: string | null;
    instagramHandle?: string | null;
    mainImage?: (number | null) | Media;
    secondaryImage?: (number | null) | Media;
    video?: (number | null) | Media;
  };
  coaches?: {
    heading?: string | null;
    subtext?: string | null;
    items?:
      | {
          eyebrow?: string | null;
          name: string;
          /**
           * Korte introductie: waar deze coach vandaan komt, wat haar eigen weg was en waarom ze coacht.
           */
          paragraph1: string;
          /**
           * Hoe ze werkt, waar klanten haar het meest voor waarderen en bij welk type vraag ze het beste past.
           */
          paragraph2?: string | null;
          specialisme?: string | null;
          ervaring?: string | null;
          instagramHandle?: string | null;
          mainImage?: (number | null) | Media;
          secondaryImage?: (number | null) | Media;
          video?: (number | null) | Media;
          reversed?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  values?: {
    heading?: string | null;
    subtext?: string | null;
    items?:
      | {
          title: string;
          text: string;
          highlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  closing?: {
    heading?: string | null;
    text?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programma".
 */
export interface Programma {
  id: number;
  /**
   * Verberg dit voor bezoekers. Alleen ingelogde beheerders kunnen het dan nog bekijken.
   */
  private?: boolean | null;
  hero?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: string | null;
    image?: (number | null) | Media;
  };
  stats?:
    | {
        value: string;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  whatIsIt?: {
    heading?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
    coreLabel?: string | null;
    coreTags?:
      | {
          label: string;
          highlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  whyNotWorking?: {
    heading?: string | null;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    closingStatement?: string | null;
  };
  method?: {
    heading?: string | null;
    subtext?: string | null;
    image?: (number | null) | Media;
    items?:
      | {
          title: string;
          text: string;
          highlight?: boolean | null;
          id?: string | null;
        }[]
      | null;
    closingStatement?: string | null;
  };
  forYou?: {
    heading?: string | null;
    subtext?: string | null;
    doHeading?: string | null;
    doItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    dontHeading?: string | null;
    dontItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  whatYouGet?: {
    heading?: string | null;
    items?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    image?: (number | null) | Media;
  };
  timeline?: {
    heading?: string | null;
    phases?:
      | {
          /**
           * Bijv. "01 — Start"
           */
          label: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    closingStatement?: string | null;
  };
  community?: {
    heading?: string | null;
    text?: string | null;
    photos?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    tags?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  results?: {
    heading?: string | null;
    items?:
      | {
          image?: (number | null) | Media;
          /**
           * Bijv. "-11 kg + meer vertrouwen + eindelijk consistent"
           */
          resultText: string;
          quoteText: string;
          id?: string | null;
        }[]
      | null;
  };
  faq?: {
    heading?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  closing?: {
    heading?: string | null;
    text?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resultaten".
 */
export interface Resultaten {
  id: number;
  /**
   * Verberg dit voor bezoekers. Alleen ingelogde beheerders kunnen het dan nog bekijken.
   */
  private?: boolean | null;
  hero?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * Meerdere foto's wisselen automatisch af in de hero.
     */
    slides?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  stats?:
    | {
        value: string;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  beforeAfter?: {
    heading?: string | null;
    subtext?: string | null;
    items?:
      | {
          beforeImage?: (number | null) | Media;
          afterImage?: (number | null) | Media;
          /**
           * Bijv. "Lois, 32 jaar"
           */
          name: string;
          quote: string;
          tags?:
            | {
                label: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  beyondPhotos?: {
    heading?: string | null;
    subtext?: string | null;
    items?:
      | {
          /**
           * Bijv. "Gedrag"
           */
          label: string;
          title: string;
          before: string;
          after: string;
          id?: string | null;
        }[]
      | null;
  };
  stories?: {
    heading?: string | null;
    items?:
      | {
          /**
           * Bijv. "Verhaal 01"
           */
          eyebrowLabel: string;
          name: string;
          whereStarted: string;
          whatChanged: string;
          whereNow: string;
          resultText?: string | null;
          duration?: string | null;
          coachName?: string | null;
          mainImage?: (number | null) | Media;
          secondaryImage?: (number | null) | Media;
          tertiaryImage?: (number | null) | Media;
          reversed?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  videoStories?: {
    heading?: string | null;
    subtext?: string | null;
    items?:
      | {
          video?: (number | null) | Media;
          name: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  quotes?:
    | {
        quote: string;
        /**
         * Bijv. "Lois, 32 — 26 weken Rebuild"
         */
        attribution: string;
        variant?: ('outline' | 'highlight' | 'muted') | null;
        id?: string | null;
      }[]
    | null;
  metrics?: {
    heading?: string | null;
    subtext?: string | null;
    items?:
      | {
          label: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  closing?: {
    heading?: string | null;
    text?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "styling_select".
 */
export interface StylingSelect<T extends boolean = true> {
  colors?:
    | T
    | {
        pageBackground?: T;
        cardBackground?: T;
        lightCard?: T;
        cardGradientFrom?: T;
        cardGradientTo?: T;
        standardBorder?: T;
        thinDivider?: T;
        bronzeBorder?: T;
        primaryText?: T;
        mutedBodyText?: T;
        smallText?: T;
        vagueLabels?: T;
        darkTextOnIvory?: T;
        navyTextOnGold?: T;
        primaryGold?: T;
        goldHover?: T;
        lightGold?: T;
        lightGoldHover?: T;
        starRating?: T;
      };
  typography?:
    | T
    | {
        headingFontFamily?: T;
        headingWeights?: T;
        headingWeight?: T;
        headingLetterSpacing?: T;
        wordmarkLetterSpacing?: T;
        bodyFontFamily?: T;
        bodyWeights?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  companyName?: T;
  logo?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?:
          | T
          | {
              street?: T;
              postalCode?: T;
              city?: T;
              country?: T;
            };
        legalName?: T;
        kvkNumber?: T;
        vatNumber?: T;
      };
  socialMedia?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
        columns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        legalLinks?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
            };
        copyrightText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  showCta?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta_select".
 */
export interface CtaSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  buttonLabel?: T;
  buttonUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  canonicalURL?: T;
  noIndex?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  private?: T;
  hero?:
    | T
    | {
        ratingValue?: T;
        ratingLabel?: T;
        heading?: T;
        intro?: T;
        image?: T;
        memberBadgeText?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  problem?:
    | T
    | {
        heading?: T;
        intro1?: T;
        intro2?: T;
        cards?:
          | T
          | {
              title?: T;
              text?: T;
              highlight?: T;
              id?: T;
            };
      };
  philosophy?:
    | T
    | {
        heading?: T;
        paragraph1?: T;
        paragraph2?: T;
      };
  pillars?:
    | T
    | {
        heading?: T;
        subtext?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              image?: T;
              reversed?: T;
              id?: T;
            };
      };
  journey?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        image?: T;
        steps?:
          | T
          | {
              phase?: T;
              title?: T;
              text?: T;
              highlight?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              quote?: T;
              id?: T;
            };
      };
  community?:
    | T
    | {
        heading?: T;
        subtext?: T;
        memberCountText?: T;
        memberCountLabel?: T;
        photos?:
          | T
          | {
              image?: T;
              id?: T;
            };
        starsHeading?: T;
        starsSubtext?: T;
        starsVideos?:
          | T
          | {
              video?: T;
              id?: T;
            };
      };
  aboutSam?:
    | T
    | {
        heading?: T;
        paragraph1?: T;
        paragraph2?: T;
        closingLine?: T;
        horizontalImage?: T;
        image1?: T;
        image2?: T;
        bottomImage?: T;
      };
  team?:
    | T
    | {
        heading?: T;
        subtext?: T;
        groupImage?: T;
        members?:
          | T
          | {
              image?: T;
              name?: T;
              role?: T;
              bio?: T;
              id?: T;
            };
      };
  content?:
    | T
    | {
        heading?: T;
        videos?:
          | T
          | {
              video?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        heading?: T;
        subtext?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  private?: T;
  hero?:
    | T
    | {
        ratingValue?: T;
        ratingLabel?: T;
        heading?: T;
        intro?: T;
        image?: T;
        memberBadgeText?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  problem?:
    | T
    | {
        heading?: T;
        intro1?: T;
        intro2?: T;
        cards?:
          | T
          | {
              title?: T;
              text?: T;
              highlight?: T;
              id?: T;
            };
      };
  philosophy?:
    | T
    | {
        heading?: T;
        paragraph1?: T;
        paragraph2?: T;
      };
  pillars?:
    | T
    | {
        heading?: T;
        subtext?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              image?: T;
              reversed?: T;
              id?: T;
            };
      };
  journey?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        image?: T;
        steps?:
          | T
          | {
              phase?: T;
              title?: T;
              text?: T;
              highlight?: T;
              id?: T;
            };
      };
  results?:
    | T
    | {
        heading?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  stories?:
    | T
    | {
        heading?: T;
        subtext?: T;
        items?:
          | T
          | {
              eyebrowLabel?: T;
              title?: T;
              text?: T;
              name?: T;
              photos?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              quote?: T;
              id?: T;
            };
      };
  community?:
    | T
    | {
        heading?: T;
        subtext?: T;
        memberCountText?: T;
        memberCountLabel?: T;
        photos?:
          | T
          | {
              image?: T;
              id?: T;
            };
        starsHeading?: T;
        starsSubtext?: T;
        starsVideos?:
          | T
          | {
              video?: T;
              id?: T;
            };
      };
  aboutSam?:
    | T
    | {
        heading?: T;
        paragraph1?: T;
        paragraph2?: T;
        closingLine?: T;
        horizontalImage?: T;
        image1?: T;
        image2?: T;
        bottomImage?: T;
      };
  team?:
    | T
    | {
        heading?: T;
        subtext?: T;
        groupImage?: T;
        members?:
          | T
          | {
              image?: T;
              name?: T;
              role?: T;
              bio?: T;
              id?: T;
            };
      };
  content?:
    | T
    | {
        heading?: T;
        videos?:
          | T
          | {
              video?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        heading?: T;
        subtext?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  private?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        image?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  founder?:
    | T
    | {
        eyebrow?: T;
        name?: T;
        paragraph1?: T;
        paragraph2?: T;
        specialisme?: T;
        ervaring?: T;
        instagramHandle?: T;
        mainImage?: T;
        secondaryImage?: T;
        video?: T;
      };
  coaches?:
    | T
    | {
        heading?: T;
        subtext?: T;
        items?:
          | T
          | {
              eyebrow?: T;
              name?: T;
              paragraph1?: T;
              paragraph2?: T;
              specialisme?: T;
              ervaring?: T;
              instagramHandle?: T;
              mainImage?: T;
              secondaryImage?: T;
              video?: T;
              reversed?: T;
              id?: T;
            };
      };
  values?:
    | T
    | {
        heading?: T;
        subtext?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              highlight?: T;
              id?: T;
            };
      };
  closing?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programma_select".
 */
export interface ProgrammaSelect<T extends boolean = true> {
  private?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        image?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  whatIsIt?:
    | T
    | {
        heading?: T;
        paragraph1?: T;
        paragraph2?: T;
        coreLabel?: T;
        coreTags?:
          | T
          | {
              label?: T;
              highlight?: T;
              id?: T;
            };
      };
  whyNotWorking?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        closingStatement?: T;
      };
  method?:
    | T
    | {
        heading?: T;
        subtext?: T;
        image?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              highlight?: T;
              id?: T;
            };
        closingStatement?: T;
      };
  forYou?:
    | T
    | {
        heading?: T;
        subtext?: T;
        doHeading?: T;
        doItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        dontHeading?: T;
        dontItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  whatYouGet?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        image?: T;
      };
  timeline?:
    | T
    | {
        heading?: T;
        phases?:
          | T
          | {
              label?: T;
              text?: T;
              id?: T;
            };
        closingStatement?: T;
      };
  community?:
    | T
    | {
        heading?: T;
        text?: T;
        photos?:
          | T
          | {
              image?: T;
              id?: T;
            };
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  results?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              image?: T;
              resultText?: T;
              quoteText?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  closing?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resultaten_select".
 */
export interface ResultatenSelect<T extends boolean = true> {
  private?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        slides?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  beforeAfter?:
    | T
    | {
        heading?: T;
        subtext?: T;
        items?:
          | T
          | {
              beforeImage?: T;
              afterImage?: T;
              name?: T;
              quote?: T;
              tags?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  beyondPhotos?:
    | T
    | {
        heading?: T;
        subtext?: T;
        items?:
          | T
          | {
              label?: T;
              title?: T;
              before?: T;
              after?: T;
              id?: T;
            };
      };
  stories?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              eyebrowLabel?: T;
              name?: T;
              whereStarted?: T;
              whatChanged?: T;
              whereNow?: T;
              resultText?: T;
              duration?: T;
              coachName?: T;
              mainImage?: T;
              secondaryImage?: T;
              tertiaryImage?: T;
              reversed?: T;
              id?: T;
            };
      };
  videoStories?:
    | T
    | {
        heading?: T;
        subtext?: T;
        items?:
          | T
          | {
              video?: T;
              name?: T;
              description?: T;
              id?: T;
            };
      };
  quotes?:
    | T
    | {
        quote?: T;
        attribution?: T;
        variant?: T;
        id?: T;
      };
  metrics?:
    | T
    | {
        heading?: T;
        subtext?: T;
        items?:
          | T
          | {
              label?: T;
              text?: T;
              id?: T;
            };
      };
  closing?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}